version: '3'
 
services:
  grafana-reporter:
    image: izakmarais/grafana-reporter
    volumes:
      - /opt/grafana-reporter/reports:/mnt/grafana-reporter:rw
    network_mode: "host"
    ports:
      - "8686:8686"
