Vagrant.configure("2") do |config|
  # --> print IP-Address <--
  config.trigger.after :up do |trigger|
    trigger.name = "IP-Address"
    trigger.info = "the vm has following ip address:"
    trigger.run_remote = {inline: "ip_a=$(hostname -I | awk '{print $2}') && echo $ip_a"}
  end

  config.vm.box = "debian/buster64"
  #config.vm.synced_folder "gitlab-sync", "/gitlab-sync", create: true
  config.vm.network "private_network", type: "dhcp"
  config.vm.define "freeipa-01" do |ipa1|
    ipa1.vm.hostname = "freeipa-01"
  end
  config.vm.define "freeipa-02" do |ipa2|
    ipa2.vm.hostname = "freeipa-02"
  end
end
