---
- hosts: 
  become: true
  vars:
    username: 
    usergroup: 
    password_hash:
    ssh_pubkey: 
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
  tasks:
    - name: create user - "{{username}}"
      user:
        name: "{{username}}"
        password: "{{password_hash}}"
        create_home: true
        append: true
        groups: adm,sudo
        shell: /bin/bash

    - name: create ssh directory
      file:
        path: /home/{{username}}/.ssh/
        state: directory
        mode: '0750'
        owner: "{{username}}"
        group: "{{usergroup}}"

    - name: provide ssh key
      copy:
        dest: /home/{{username}}/.ssh/authorized_keys
        content: "{{ssh_pubkey}}"
        mode: '0600'
        owner: "{{username}}"
        group: "{{usergroup}}"

    - name: configure sshd
      lineinfile:
          path: /etc/ssh/sshd_config
          insertbefore: 'PubkeyAuthentication yes'
          regexp: '^#AuthorizedKeysFile'
          line: 'AuthorizedKeysFile     %h/.ssh/authorized_keys'
      notify:
        - restart sshd

    - name: set timezone Europe/Berlin
      timezone:
        name: Europe/Berlin

    - name: show ip adress
      debug:
          var: hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address']
