---
- name: create a second partition on /dev/sda
  parted:
      device: /dev/sda
      part_start: 134215680s
      part_end: 100%
      align: optimal
      number: 2
      state: present
      flags: lvm

- name: create pv /dev/sda2
  lvg:
      vg: "{{ vg_name }}"
      pvs: /dev/sda1,/dev/sda2
      pv_options: C
      state: present

- name: extend the logical volume "{{ lv_name }}"
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    size: +100%FREE
    resizefs: true